### ISSUE TITLE
Data format sample

### ISSUE THREAD

**Issue by napsternxg** [aschein/pgds#4]
@aschein I think it would be easier to run the code if there is a small sample data included or the format of the data is mentioned.

**Comment by aschein** [comment]
Sorry for the delay!

I've added some sample ICEWS data [here](https://github.com/aschein/pgds/tree/master/dat/icews/undirected/2003-D) and [a Jupyter notebook](https://github.com/aschein/pgds/blob/master/src/icews_example.ipynb) that shows how to use the code to do exploratory and predictive tasks on the data.

**Comment by napsternxg** [comment]
@aschein thanks a lot. This is really useful. I will play around with this.
